// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGUpE-dLde85dj8J4fNZKNUiUld_l-q1M',
    appId: '1:982159595377:web:3e37ac06cc9273b0ee88d0',
    messagingSenderId: '982159595377',
    projectId: 'goalforge-a9fd9',
    authDomain: 'goalforge-a9fd9.firebaseapp.com',
    storageBucket: 'goalforge-a9fd9.firebasestorage.app',
    measurementId: 'G-8QCS7NJ52L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMsb8B0JtnORRhMRLM5hEL07gz8yqp9GM',
    appId: '1:982159595377:android:27285ed7891ff7e8ee88d0',
    messagingSenderId: '982159595377',
    projectId: 'goalforge-a9fd9',
    storageBucket: 'goalforge-a9fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8md0yAGn_qEgVUO6Ug96jIcSJ1WUlTc',
    appId: '1:982159595377:ios:1ee0c0efbdacb674ee88d0',
    messagingSenderId: '982159595377',
    projectId: 'goalforge-a9fd9',
    storageBucket: 'goalforge-a9fd9.firebasestorage.app',
    iosBundleId: 'com.example.goalForge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGUpE-dLde85dj8J4fNZKNUiUld_l-q1M',
    appId: '1:982159595377:web:51c8da104b0c9e81ee88d0',
    messagingSenderId: '982159595377',
    projectId: 'goalforge-a9fd9',
    authDomain: 'goalforge-a9fd9.firebaseapp.com',
    storageBucket: 'goalforge-a9fd9.firebasestorage.app',
    measurementId: 'G-7EYM08GXTP',
  );
}
